In [ ]:
import tensorflow as tf
import numpy as np


tf.nn.conv2d(input, filter, strides, padding, use_cudnn_on_gpu=None, name=None)
<font color=red>第一个参数input：</font>
   指需要做卷积的输入图像，它要求是一个Tensor，具有[batch, in_height, in_width, in_channels]这样的    shape，具体    含义是[训练时一个batch的图片数量, 图片高度, 图片宽度, 图像通道数]，注意这是一个4维的Tensor，要求类    型为        float32和float64其中之一
<font color=red> 第二个参数filter：</font>
相当于CNN中的卷积核，它要求是一个Tensor，具有[filter_height, filter_width, in_channels,            out_channels]这样的shape，具体含义是[卷积核的高度，卷积核的宽度，图像通道数，卷积核个数]，要求类型与参数input    相  同,filter的通道数要求与input的in_channels一致，有一个地方需要注意，第三维in_channels，就是参数input的第四    维

<font color=red>第三个参数strides： </font>
卷积时在图像每一维的步长，这是一个一维的向量，长度4，strides[0]=strides[3]=1

<font color=red>第四个参数padding： </font>
string类型的量，只能是"SAME","VALID"其中之一，这个值决定了不同的卷积方式（后面会介绍）

<font color=red> 第五个参数：use_cudnn_on_gpu:</font>
bool类型，是否使用cudnn加速，默认为true

<font color=red>结果返回 </font>
一个Tensor，这个输出，就是我们常说的feature map

In [41]:
#conv2d test

input=tf.Variable(tf.random_normal([1,3,3,2])) #一个3*3 的2通道图像
filter=tf.Variable(tf.random_normal([3,3,2,2])) # 使用2个3*3 的卷积核
op=tf.nn.conv2d(input,filter,strides=[1,1,1,1],padding="VALID")  #fliter 作用于input 上将会输出3个3*3 的feature-map 
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print("input=",input.eval())
    print("filter=",filter.eval())
    print("result=",sess.run(op))


input= [[[[-0.34493417 -0.10738501]
   [-0.85022193  1.71712673]
   [-0.60275549  0.19930522]]

  [[ 0.32434443  0.93755305]
   [-0.44820955 -0.64372748]
   [ 0.58225816  0.13690184]]

  [[-1.20702815  0.46286833]
   [ 0.46935585  1.34038448]
   [-0.56047243  1.21324253]]]]
filter= [[[[ 0.98620719  0.32378533]
   [ 0.5578512  -1.12953448]]

  [[-0.28526396  0.17154564]
   [-1.51936436 -2.30176568]]

  [[-2.34293437 -0.70343775]
   [-1.07427549  1.67923558]]]


 [[[-0.485277    1.11246312]
   [ 0.02792515  0.75532722]]

  [[-0.26506284 -1.46572471]
   [ 0.10474318 -0.45718116]]

  [[-0.90435976 -0.99199212]
   [-0.87528074 -1.73675561]]]


 [[[ 0.65318054  0.14416404]
   [-0.6814785  -0.43309295]]

  [[-1.63798225  2.07280302]
   [ 0.26454189  0.65028101]]

  [[-0.90376294 -0.58944052]
   [-0.62296063  0.97574115]]]]
result= [[[[-4.06193161  0.85909855]]]]


In [ ]:
#矩阵乘法
from numpy import *
A=mat(random.rand(10,10))
x=mat(random.rand(10,1))
print(x)
b=A*x
print(b)